services:
  # 1. 로그 저장소 (창고)
  loki:
    image: grafana/loki:2.9.1
    container_name: pgsg-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
    networks:
      - pgsg-network

  # 2. 로그 수집기 (배달원: Kafka -> Loki), 현재는 kafka 연결 실패로 파일 로그에서 loki로 보내는 방식 사용 중
  promtail:
    image: grafana/promtail:2.9.1
    container_name: pgsg-promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /home/yjj1544/app/product/logs:/logs
    command: -config.file=/etc/promtail/config.yml
#    environment:
#      - BOOTSTRAP_SERVERS=${BOOTSTRAP_SERVERS} # 환경변수 처리
    depends_on:
      - loki
    networks:
      - pgsg-network

  # 3. 메트릭 수집
  prometheus:
    image: prom/prometheus
    container_name: pgsg-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
      - prometheus-data:/prometheus
    networks:
      - pgsg-network

  # 4. 시각화 도구 (관제 화면)
  grafana:
    image: grafana/grafana:latest
    container_name: pgsg-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
      - prometheus
    networks:
      - pgsg-network

  # 5. 알림 관리
  alertmanager:
    image: prom/alertmanager
    container_name: pgsg-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - pgsg-network

  alertmanager-discord:
    image: benjojo/alertmanager-discord
    container_name: pgsg-alertmanager-discord
    environment:
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
    networks:
      - pgsg-network

  # 6. zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: pgsg-zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_USE_SSL=false
      - MYSQL_JDBC_URL=jdbc:mysql://${ZIPKIN_DB_USER}:${ZIPKIN_DB_PASSWORD}@zipkin-db:3306/zipkin?allowPublicKeyRetrieval=true&useSSL=false
    networks:
      - pgsg-network
    depends_on:
      zipkin-db:
          condition: service_healthy

  zipkin-db:
    image: mysql:8
    container_name: pgsg-zipkin-db
    environment:
      - MYSQL_ROOT_PASSWORD=${ZIPKIN_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=zipkin
      - MYSQL_USER=${ZIPKIN_DB_USER}
      - MYSQL_PASSWORD=${ZIPKIN_DB_PASSWORD}
    volumes:
      - zipkin-db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pgsg-network

networks:
  pgsg-network:
    external: true

volumes:
  loki-data:
  prometheus-data:
  grafana-data:
  zipkin-db-data: